networks:
  app-network:
    driver: bridge

services:
  backend:
    container_name: backend
    image: php:8.2-apache
    build: 
      context: .
      dockerfile: Dockerfile.api
    restart: unless-stopped
    env_file:
      - "./uptrips_api/laravel-app/.env"
    volumes: 
      - ./uptrips_api/laravel-app:/var/www
    ports:
      - 8001:80
    networks: 
      - app-network

  mysql:
    container_name: mysql
    image: mysql:latest  # Imagem oficial do MySQL
    ports:
      - "3306:3306"  # Mapeia a porta 3306 do host para a porta 3306 do container
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config/mysql-init:/docker-entrypoint-initdb.d    
    networks:
      - app-network
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=uptrips_viagens
      - MYSQL_USER=uptrips
      - MYSQL_PASSWORD=password

  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./uptrips_frontend/app:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    networks: 
      - app-network
      

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 3080:80
    networks:
      - app-network
    environment:
      - PMA_HOST=mysql  
      - PMA_USER=uptrips  
      - PMA_PASSWORD=password 

volumes:
  mysql_data:
